name: Generate requirements.txt
on:
  pull_request:
    branches:
      - 'develop'
      - 'master'
jobs:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@4
      with:
        python-version: '3.10'

    - name: Install pipenv
      run: |
        pip install pipenv

    - name: Generate requirements.txt
      run: |
        pipenv requirements > src/requirements.txt
